version: '3.8'


services:
  app:
    env_file: ".env"
    build: .
    container_name: invoices
    ports:
      - "8181:8181"
    depends_on:
      - mongodb 

  mongodb:
    container_name: ${COINTAINER_NAME}
    image: "mongo:4.2.16-bionic"
    environment:
      - MONGO_INITDB_DATABASE=${MONGO_DB}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_DB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_DB_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: {}